name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.7.1

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: Run linter
        run: pnpm lint
